version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    volumes:
      # Persist session data
      - ./session:/app/session
      # Persist data directory
      - ./data:/app/data
      # Persist baileys store
      - ./baileys_store.json:/app/baileys_store.json
    environment:
      # Add your environment variables here
      - NODE_ENV=production
      # If you have other env variables in settings.js, add them here
      # - OWNER_NUMBER=your_number
      # - BOT_NAME=your_bot_name
    # Uncomment if you need to expose ports
    # ports:
    #   - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"